### ISSUE TITLE
team login error

### ISSUE THREAD

**Issue by gimli2** [pozda2/HKSova#1]
Kdyz vlezu na `http://127.0.0.1:5000/2022/login/` nebo `http://127.0.0.1:5000/login/` v obou pripadech to nezvladne sestavit url: `werkzeug.routing.BuildError: Could not build url for endpoint 'team_.view_login'. Did you mean 'team.view_login' instead?`. Asi se nejak neinicializuje ten rok a pak sablona pinda:
```
File "~/hksova-python/hksova/templates/Team/login.jinja", line 6, in block 'main'
<form {{url_for('team_' ~ year ~ ".view_login")}} method="post">
```

**Comment by pozda2** [comment]
Hotovo
