### ISSUE TITLE
images - static nově nahrané soubory nejsou vidět do restartu aplikace

### ISSUE THREAD

**Issue by pozda2** [pozda2/HKSova#7]

**Comment by gimli2** [comment]
Funguje az po restartu containeru s --build flagem. Asi by chtelo najit lepsi cestu, jak nemuset kvuli statickym souborum rebuildovat. Nejaky mapovani slozky z hosta do containeru?

Dockerfile:
`ADD ./hksova/static/ /usr/src/app/hksova/static`

A vlastne, nestacilo by nechat venku i zbytek kodu? Minimalne by to urychlilo build.

**Comment by gimli2** [comment]
Vyreseno upravou `docker-compose.yml` (a odebranil kopirovani tehoz z `Dockerfile`) zhruba takto:
```
volumes:
            - ./hksova:/usr/src/app/hksova
```
viz  commit 6dbdd86db6a70732724100d92ca04124f1b17f92

**Comment by gimli2** [comment]
Volumes nereflekuji primo zmeny na FS, viz:
https://forums.docker.com/t/how-to-apply-changes-to-my-code-automatically-in-my-container-without-restarting-it/139875/4

takze spravna cesta bude spis pres `bind`
```
volumes:
      - type: bind
        source: ./static
        target: /opt/app/static
```

**Comment by gimli2** [comment]
Funguje v kombinaci s `flask_app.config['TEMPLATES_AUTO_RELOAD'] = True`, ale jen pro templaty. Zmenu pythonoveho kodu to nezaregistruje...

**Comment by gimli2** [comment]
Tak nakonec pomohlo 
```
[uwsgi]
py-autoreload = 1
```
